apiVersion: apps/v1  
kind: Deployment  
metadata:
  name: generator-app  
spec:
  # replicas: 2  
  selector:
    matchLabels:
      app: generator-app
  template:
    metadata:
      labels:
        app: generator-app  
    spec:
      containers:
      - name: generator-app  
        image: yoonseohan/generator:latest
        imagePullPolicy: IfNotPresent
        args: ["uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: generator-secret  