apiVersion: v1
kind: Service
metadata:
  name: generator-service
  labels:
    app: generator-app
    component: generator
spec:
  type: ClusterIP
  selector:
    app: generator-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000