apiVersion: v1  
kind: Service  
metadata:
  name: generator-service 
spec:
  type: LoadBalancer  
  selector:
    app: generator-app  
  ports:
  - protocol: TCP  
    port: 8000  
    targetPort: 8000  