apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever-app
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: retriever-app
  template:
    metadata:
      labels:
        app: retriever-app
    spec:
      containers:
      - name: retriever-app
        image: yoonseohan/retriever-poc:latest
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000