apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever-app
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: retriever-app
  template:
    metadata:
      labels:
        app: retriever-app
    spec:
      containers:
      - name: retriever-app
        image: yoonseohan/retriever-poc:latest
        imagePullPolicy: IfNotPresent
        args: ["uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8000