apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever-app
  labels:
    app: retriever-app
    component: retriever
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: retriever-app
  template:
    metadata:
      labels:
        app: retriever-app
        component: retriever
    spec:
      containers:
      - name: retriever-app
        image: yoonseohan/distributed-rag-retriever:latest
        imagePullPolicy: Always
        args: ["uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: retriever-secret
        - configMapRef:
            name: retriever-config