apiVersion: v1
kind: Service
metadata:
  name: retriever-service
  labels:
    app: retriever-app
    component: retriever
spec:
  type: ClusterIP
  selector:
    app: retriever-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000