apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
data:
  GENERATOR_URL: http://generator-service:80/generate
  RETRIEVER_NEWS_URL: http://news-retriever-service:80/query
  RETRIEVER_FINANCE_URL: http://finance-retriever-service:80/query
  RETRIEVER_LAW_URL: http://law-retriever-service:80/query