apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  labels:
    app: orchestrator-app
    component: orchestrator
data:
  GENERATOR_URL: http://generator-service:8000/generate
  RETRIEVER_PROJ_SPEC_URL: http://retriever-proj-spec-service:8000/query
  RETRIEVER_TECH_CONCEPT_URL: http://retriever-tech-concept-service:8000/query
  RETRIEVER_DEV_LOG_URL: http://retriever-dev-log-service:8000/query
  RETRIEVER_OPS_TS_URL: http://retriever-ops-ts-service:8000/query