apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-app
  labels:
    app: orchestrator-app
    component: orchestrator
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: orchestrator-app
  template:
    metadata:
      labels:
        app: orchestrator-app
        component: orchestrator
    spec:
      containers:
      - name: orchestrator-app
        image: yoonseohan/orchestrator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        args: ["uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]
        envFrom:
        - configMapRef:
            name: orchestrator-config